project1
egorwar/TinkoffJavaProjectTemplate pull request #5
Opened 2023-10-22 18:16 UTC by egorwar

На счёт тестов: сделал только на исключения, поскольку для тестов на корректную работу нужно напрямую лезть в private поля и методы и менять их значения. Вроде это как-то можно делать в тестах, но стоит ли? Или стоит сделать их публичными? Не понимаю ...

2023-10-24 18:38 UTC, psharaev requested changes
Тесты в проектах само по себе сложно писать. Для этого стоит завести весьма много интерфейсов (лишь одна из техник), что бы условно на проде ваши реализации использовались, а в тестах подсовывались тестовые реализации для проверки поведения

2023-10-24 18:38 UTC, psharaev commented on src/main/java/edu/project1/Game.java
> +
Пожалуй, хорошей будет декомпозицией создание класса HangmanGame (всё же играть в виселицу можно не только в консоли), которому в конструктор можно будет передать игрока и загаданное слово.

1. Следует создать интерфейс игрока. Создать класс HumanPlayer (или ConsolePlayer). Если захотите можете для себя создать RandomPlayer;
2. 
Такая декомпзиция позволит вам очень ловко создавать различные конфигурации игры, не сильно меняя код

2023-10-27 05:07 UTC, egorwar commented
Добавил интерфейс Player, описывающий 2 метода: передать ответ пользователя и вернуть ответ игры. Так, получилось вынести работу с консолью в ConsolePlayer. Кроме того, создал MockPlayer, эмулирующий работу с консолью. С его помощью получилось всё покрыть тестами.

2023-10-28 09:07 UTC, psharaev commented
Хорошая работа, принято. У меня нет прав на слияние PR. Можете, пожалуйста, сделать merge

2023-10-28 09:33 UTC, merged